const products=[
{id:1,title:"Black Legacy Tracksuit",desc:"Zip hoodie · Crest trouser",price:168,cat:"black sets",badge:"Limited",img:"assets/dapor-black-tracksuit.webp"},
{id:2,title:"Ivory Heritage Tracksuit",desc:"Bomber · Hoodie · Relaxed trouser",price:178,cat:"ivory sets",badge:"New",img:"assets/dapor-ivory-tracksuit.webp"},
{id:3,title:"Onyx Crest Hoodie",desc:"Premium heavyweight cotton",price:98,cat:"black",img:"assets/dapor-black-tracksuit.webp"},
{id:4,title:"Ivory Signature Hoodie",desc:"Warm beige · Gold crest",price:108,cat:"ivory",img:"assets/dapor-ivory-tracksuit.webp"},
{id:5,title:"Founders Crest Trousers",desc:"Tapered fit · Embroidered thigh",price:88,cat:"black sets",badge:"Bestseller",img:"assets/dapor-black-tracksuit.webp"},
{id:6,title:"Heritage Bomber Set",desc:"Layered bomber · Hoodie · Trouser",price:198,cat:"ivory accessories",img:"assets/dapor-ivory-tracksuit.webp"}
];
const reviewData=[
{q:"The weight and finish feel exceptional. It has the presence of a luxury piece, but I can actually live in it.",name:"Marcus T.",item:"Black Legacy Tracksuit"},
{q:"The ivory set looks even better in person. Clean fit, beautiful detail, and it arrived like a genuine luxury purchase.",name:"Aaliyah R.",item:"Ivory Heritage Tracksuit"},
{q:"I bought the hoodie for a trip and ended up wearing it the whole weekend. Compliments every time.",name:"Jordan C.",item:"Onyx Crest Hoodie"}
];
let cart=[];let reviewIndex=0;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function productCard(p){return `<article class="product-card reveal" data-cat="${p.cat}"><div class="product-image">${p.badge?`<span class="badge">${p.badge}</span>`:""}<button class="wishlist" aria-label="Add ${p.title} to wishlist">♡</button><img src="${p.img}" alt="${p.title}" loading="lazy"></div><div class="product-info"><span class="product-kicker">DA’POR edition 01</span><h3>${p.title}</h3><p>${p.desc}</p><div class="product-bottom"><span class="price">$${p.price}.00</span><span class="rating">★★★★★ 4.9</span></div><button class="add-to-cart" data-id="${p.id}">Add to bag</button></div></article>`}
function renderProducts(filter="all"){const list=filter==="all"?products:products.filter(p=>p.cat.includes(filter));$(".product-grid").innerHTML=list.map(productCard).join("");$(".product-total").textContent=`${list.length} pieces`;bindCards();observeReveals()}
function bindCards(){$$(".wishlist").forEach(b=>b.onclick=()=>{b.classList.toggle("active");b.textContent=b.classList.contains("active")?"♥":"♡"});$$('.add-to-cart').forEach(b=>b.onclick=()=>addToCart(+b.dataset.id,b))}
function addToCart(id,button){const p=products.find(x=>x.id===id);const found=cart.find(x=>x.id===id);found?found.qty++:cart.push({...p,qty:1});button.classList.add("added");button.textContent="✓ Added";setTimeout(()=>{button.classList.remove("added");button.textContent="Add to bag"},1200);updateCart();showToast(`${p.title} added to your bag`)}
function updateCart(){const count=cart.reduce((a,x)=>a+x.qty,0);$(".cart-count").textContent=count;const wrap=$(".cart-items");const summary=$(".cart-summary");if(!cart.length){wrap.innerHTML=`<div class="empty-cart"><span>0</span><h3>Your bag is waiting.</h3><p>Explore the first DA’POR edition.</p><a href="#new" class="button black close-and-shop">Shop the drop</a></div>`;summary.hidden=true;$(".close-and-shop").onclick=closePanels;return}wrap.innerHTML=cart.map(x=>`<div class="cart-line"><img src="${x.img}" alt=""><div><span class="product-kicker">Qty ${x.qty}</span><h3>${x.title}</h3><p>${x.desc}</p><button data-remove="${x.id}">Remove</button></div><strong>$${x.price*x.qty}.00</strong></div>`).join("");$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);updateCart()});const total=cart.reduce((a,x)=>a+x.price*x.qty,0);$(".subtotal").textContent=`$${total}.00`;summary.hidden=false}
function openCart(){closePanels();$(".cart-drawer").classList.add("open");$(".cart-drawer").setAttribute("aria-hidden","false");$(".overlay").classList.add("open");document.body.classList.add("lock")}
function closePanels(){$$(".cart-drawer,.search-panel,.mobile-menu").forEach(x=>{x.classList.remove("open");x.setAttribute("aria-hidden","true")});$(".overlay").classList.remove("open");document.body.classList.remove("lock")}
function openCheckout(){const total=cart.reduce((a,x)=>a+x.price*x.qty,0);$(".checkout-items").innerHTML=cart.map(x=>`<div class="checkout-line"><img src="${x.img}" alt=""><span>${x.title}<br>Qty ${x.qty}</span><strong>$${x.price*x.qty}.00</strong></div>`).join("");$(".order-total strong").textContent=`$${total}.00`;closePanels();$(".checkout-modal").classList.add("open");$(".checkout-modal").setAttribute("aria-hidden","false");$(".overlay").classList.add("open");document.body.classList.add("lock");prepareStripeCheckout(total)}
function closeCheckout(){$(".checkout-modal").classList.remove("open");$(".checkout-modal").setAttribute("aria-hidden","true");$(".overlay").classList.remove("open");document.body.classList.remove("lock")}
let stripe=null,cardNumberEl=null,cardExpiryEl=null,cardCvcEl=null,paymentRequest=null,stripeConfig=null;
const stripeFieldStyle="height:50px;background:#fff;border:1px solid #d6d0c4;margin-top:7px;padding:0 14px;display:flex;align-items:center;width:100%;box-sizing:border-box";
function styleStripeFields(){["card-number","card-expiry","card-cvc"].forEach(id=>{const el=document.getElementById(id);if(el)el.style.cssText=stripeFieldStyle})}
function checkoutCustomer(form,extra={}){return{email:extra.email||form.email.value,firstName:extra.firstName||form.firstName.value,lastName:extra.lastName||form.lastName.value,address:extra.address||form.address.value,city:extra.city||form.city.value,zip:extra.zip||form.zip.value}}
async function loadStripeConfig(){if(stripeConfig)return stripeConfig;try{const res=await fetch("/api/config");stripeConfig=await res.json()}catch(e){stripeConfig={publishableKey:"",configured:false}}return stripeConfig}
async function createPaymentIntent(customer){const res=await fetch("/api/create-payment-intent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart.map(x=>({id:x.id,qty:x.qty})),customer})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not start payment");return data}
function completePaidOrder(){cart=[];updateCart();closeCheckout();showToast("Order confirmed — thank you")}
function mountCardElements(){if(cardNumberEl||!stripe)return;const elements=stripe.elements();const style={base:{fontFamily:"Manrope, Arial, sans-serif",fontSize:"14px",color:"#11100e","::placeholder":{color:"#9a9388"}}};cardNumberEl=elements.create("cardNumber",{style,placeholder:"Card number"});cardExpiryEl=elements.create("cardExpiry",{style,placeholder:"MM / YY"});cardCvcEl=elements.create("cardCvc",{style,placeholder:"CVC"});cardNumberEl.mount("#card-number");cardExpiryEl.mount("#card-expiry");cardCvcEl.mount("#card-cvc")}
async function setupWallets(totalCents){const wallet=$("#wallet-element");if(!wallet||!stripe)return;if(paymentRequest){paymentRequest.update({total:{label:"DA'POR Millionaires",amount:totalCents}});return}paymentRequest=stripe.paymentRequest({country:"US",currency:"usd",total:{label:"DA'POR Millionaires",amount:totalCents},requestPayerName:true,requestPayerEmail:true,requestShipping:true,shippingOptions:[{id:"standard",label:"Complimentary shipping",detail:"US delivery",amount:0}]});const canPay=await paymentRequest.canMakePayment();if(!canPay)return;const prButton=stripe.elements().create("paymentRequestButton",{paymentRequest,style:{paymentRequestButton:{type:"buy",theme:"light",height:"50px"}}});wallet.hidden=false;wallet.style.marginBottom="16px";prButton.mount("#wallet-element");paymentRequest.on("paymentmethod",async ev=>{const form=$("#checkout-form");const ship=ev.shippingAddress||{};const name=(ev.payerName||"").trim();const parts=name.split(" ");try{const pi=await createPaymentIntent(checkoutCustomer(form,{email:ev.payerEmail,firstName:parts[0]||form.firstName.value,lastName:parts.slice(1).join(" ")||form.lastName.value,address:(ship.addressLine||[]).join(" ")||form.address.value,city:ship.city||form.city.value,zip:ship.postalCode||form.zip.value}));const {error,paymentIntent}=await stripe.confirmCardPayment(pi.clientSecret,{payment_method:ev.paymentMethod.id},{handleActions:false});if(error){ev.complete("fail");showToast(error.message);return}ev.complete("success");if(paymentIntent.status==="requires_action"){const follow=await stripe.confirmCardPayment(pi.clientSecret);if(follow.error){showToast(follow.error.message);return}}completePaidOrder()}catch(err){ev.complete("fail");showToast(err.message||"Payment could not be completed")}})}
async function prepareStripeCheckout(total){styleStripeFields();const config=await loadStripeConfig();if(!config.publishableKey||typeof Stripe!=="function")return;if(!stripe)stripe=Stripe(config.publishableKey);mountCardElements();setupWallets(Math.round(total*100))}
function showToast(msg){const t=$(".toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function renderReview(){const r=reviewData[reviewIndex];$(".review-card blockquote").textContent=`“${r.q}”`;$(".review-card p strong").textContent=r.name;$(".review-card p span").textContent=`Verified buyer · ${r.item}`;$$('.review-avatars img').forEach((x,i)=>{x.style.transform=i===reviewIndex?'scale(1.12)':'scale(1)';x.style.borderColor=i===reviewIndex?'#b58834':'#111'})}
function corridorFrames(dir,name){const p={perspective:30,cardHeight:25,birthHeight:2.6,exitHeight:46,railBirth:-11,railExit:44,fan:3.3,turnBirth:6,turnExit:28,stops:24};const steps=[];for(let s=0;s<=p.stops;s++){const u=s/p.stops;const scale=(p.birthHeight/p.cardHeight)*Math.pow(p.exitHeight/p.birthHeight,u);const z=p.perspective*(1-1/scale);const rail=p.railExit-(p.railExit-p.railBirth)*Math.pow(1-u,p.fan);const turn=p.turnBirth+(p.turnExit-p.turnBirth)*u;steps.push(`${(u*100).toFixed(2)}%{transform:translate3d(${(dir*rail).toFixed(2)}cqw,0,${z.toFixed(2)}cqw) rotateY(${(-dir*turn).toFixed(2)}deg)}`)}return `@keyframes ${name}{${steps.join("")}}`}
function buildCorridor(){const style=document.createElement("style");style.textContent=corridorFrames(1,"daporRight")+corridorFrames(-1,"daporLeft");document.head.appendChild(style);const imgs=products.map(x=>x.img);[".stream-right",".stream-left"].forEach((sel,side)=>{const s=$(sel);s.innerHTML=Array.from({length:9},(_,i)=>`<div class="stream-card" style="animation:${side?'daporLeft':'daporRight'} 18s linear infinite;animation-delay:${-(i*18)/9}s"><img src="${imgs[i%imgs.length]}" alt=""></div>`).join("")})}
function observeReveals(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.1});$$('.reveal:not(.visible)').forEach(x=>io.observe(x))}
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});$(".cart-button").onclick=openCart;$(".cart-close").onclick=closePanels;$(".overlay").onclick=()=>{$(".checkout-modal").classList.contains("open")?closeCheckout():closePanels()};$(".search-button").onclick=()=>{closePanels();$(".search-panel").classList.add("open");$(".overlay").classList.add("open");$(".search-panel input").focus()};$(".panel-close").onclick=closePanels;$(".search-panel button:not(.panel-close)").onclick=()=>{const q=$(".search-panel input").value.toLowerCase().trim();const list=q?products.filter(p=>(p.title+p.desc+p.cat).toLowerCase().includes(q)):products;$(".product-grid").innerHTML=list.map(productCard).join("");$(".product-total").textContent=`${list.length} pieces`;bindCards();closePanels();document.querySelector("#new").scrollIntoView({behavior:"smooth"});observeReveals()};$(".account-button").onclick=()=>showToast("Member accounts will connect at launch");$(".menu-button").onclick=()=>{$(".mobile-menu").classList.add("open");document.body.classList.add("lock")};$(".menu-close").onclick=closePanels;$$('.mobile-menu a').forEach(a=>a.onclick=closePanels);$(".checkout-button").onclick=openCheckout;$(".checkout-close").onclick=closeCheckout;$(".review-arrow.next").onclick=()=>{reviewIndex=(reviewIndex+1)%reviewData.length;renderReview()};$(".review-arrow.prev").onclick=()=>{reviewIndex=(reviewIndex-1+reviewData.length)%reviewData.length;renderReview()};$("#newsletter-form").onsubmit=e=>{e.preventDefault();showToast("Welcome to the DA’POR circle");e.target.reset()};$("#checkout-form").onsubmit=async e=>{e.preventDefault();const form=e.target;const btn=form.querySelector('[type=submit]');if(!cart.length){showToast("Your bag is empty");return}if(!stripe||!cardNumberEl){showToast("Stripe is not configured yet. Add the API keys on Vercel.");return}btn.disabled=true;const original=btn.textContent;btn.textContent="Processing...";try{const pi=await createPaymentIntent(checkoutCustomer(form));const {error,paymentIntent}=await stripe.confirmCardPayment(pi.clientSecret,{payment_method:{card:cardNumberEl,billing_details:{name:`${form.firstName.value} ${form.lastName.value}`.trim(),email:form.email.value,address:{line1:form.address.value,city:form.city.value,postal_code:form.zip.value,country:"US"}}}});if(error){showToast(error.message);return}if(paymentIntent&&paymentIntent.status==="succeeded")completePaidOrder()}catch(err){showToast(err.message||"Payment could not be completed")}finally{btn.disabled=false;btn.textContent=original}};
$$('[data-shop-filter]').forEach(a=>a.addEventListener('click',()=>{const b=$(`.filter[data-filter="${a.dataset.shopFilter}"]`);if(b)b.click()}));
window.addEventListener('scroll',()=>{$('.site-header').style.background=scrollY>80?'rgba(5,5,5,.97)':'rgba(5,5,5,.92)'});styleStripeFields();renderProducts();buildCorridor();observeReveals();
